---

- name: configure the final lab osp instances
  hosts: app_servers:load_balancers:database_servers:localhost #designate control for AT, localhost otherwise 
  become: yes
  gather_facts: yes

  tasks:

    - name: test the connection
      ping:
      register: output

    - debug:
        msg: "{{ output }}"

    - name: add a line into file
      lineinfile:
        state: present
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: "{{ item }}"
      loop:
        - PEERDNS=no
#        - DNS1={{ hostvars.localhost.ansible_facts.default_ipv4.address }}
        - DNS1={{ hostvars.control.ansible_facts.default_ipv4.address }} #necessary for AT
      register: network_update

    - name: restart network manager
      service:
        name: NetworkManager
        state: restarted
      when: network_update.changed | bool

    - name: gather resolve.conf information
      command: "more /etc/resolv.conf"
      register: DNS_information

    - debug:
        msg: "{{ DNS_information }}"

    - name: install katello
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        state: latest
        disable_gpg_check: yes

    - name: configure host subscription
      redhat_subscription:
#        server_hostname: satellite.example.com
        org_id: prod
        activationkey: gpte-labs-rhel8
        state: present
        auto_attach: yes
