osp_instances:

  - server_name: app1 
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 87f8-HostSG
    internal_network: "net-name: 87f8-dev-network"
    keypair: 87f8-keypair
    metadata: "AnsibleGroup=final_lab_osp_instances,group=app_servers,deployment_name=dev"

  - server_name: app2
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 87f8-HostSG
    internal_network: "net-name: 87f8-dev-network"
    keypair: 87f8-keypair
    metadata: "AnsibleGroup=final_lab_osp_instances,group=app_servers,deployment_name=dev"

  - server_name: appdb1
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 87f8-HostSG
    internal_network: "net-name: 87f8-dev-network"
    keypair: 87f8-keypair
    metadata: "AnsibleGroup=final_lab_osp_instances,group=database_servers,deployment_name=dev"

  - server_name: frontend1
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 87f8-HostSG
    internal_network: "net-name: 87f8-dev-network"
    keypair: 87f8-keypair
    metadata: "AnsibleGroup=final_lab_osp_instances,group=load_balancers,deployment_name=dev"
